name: flutter_website
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  get: 4.6.5
  flutter:
    sdk: flutter
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.3.1
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_gen:
  output: lib/gen/
